# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './welcome.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import sys

from PyQt5 import QtCore, QtGui, QtWidgets


def get_logger(log):
    global logger
    logger = log
    logger("module.itunesrpc_window.error_no_secret logger active.")


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("ERROR")
        MainWindow.resize(523, 145)
        self.setWindowIcon(QtGui.QIcon("icon.ico"))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 521, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 50, 521, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.ok = QtWidgets.QPushButton(self.centralwidget)
        self.ok.setGeometry(QtCore.QRect(14, 110, 301, 23))
        self.ok.setObjectName("ok")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ERROR"))
        self.label.setText(_translate("MainWindow", "An Error Occurred (E.001.NS)"))
        self.label_2.setText(
            _translate(
                "MainWindow",
                '<html><head/><body><p><span style=" font-size:14pt;">Please read the README.md file packaged<br>with the download of this software.</span></p></body></html>',
            )
        )
        self.ok.setText(_translate("MainWindow", "Click here to continue."))


class Logic(QtWidgets.QMainWindow, Ui_MainWindow):
    def __init__(self, parent=None):
        logger("[ERROR-GUI] SHOWING ERROR MESSAGE")

        QtWidgets.QMainWindow.__init__(self, parent=parent)
        self.setupUi(self)
        self.ok.clicked.connect(self.close_win_error)

    def close_win_error(self):
        logger("[ERROR-GUI] Closing ERROR GUI.")
        self.close()


def start():
    error_app = QtWidgets.QApplication(sys.argv)
    error = Logic()
    error.show()
    error_app.exec_()
