name: isort
on: [pull_request, push]

jobs:
  isort:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install --user --upgrade pip wheel
      - run: pip install --user isort
      - run: isort --check-only --profile black .