name: lint_python
on: [pull_request, push]

jobs:
  lint_python:
    continue-on-error: true
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install --upgrade pip wheel
      - run: pip install bandit black codespell flake8 isort mypy pytest pyupgrade safety
      - run: bandit --recursive --skip B605,B110,B404,B602,B605,B607,B104 .
      - run: black --check . || true
      - run: codespell --ignore-words-list="wee" --skip="*.css,*.js, test.*, "
      - run: flake8 . --count --ignore=E12,E2,F40,W29,W504 --max-complexity=10 --max-line-length=156 --show-source --statistics
      - run: isort --check-only --profile black . || true
      - run: pip install psutil
      - run: pip install -e .
      - run: mkdir -p .mypy_cache
      - run: mypy --install-types --non-interactive . || true
      - run: pytest . || true
      - run: pytest --doctest-modules . || true
      - run: shopt -s globstar && pyupgrade --py36-plus **/*.py || true
      - run: safety check
